export const queryKey = {
  PRODUCTS: "PRODUCTS",
  PROFILE: "PROFILE",
  CART_INFO: "CART_INFO",
  MY_ADDRESSES: "MY_ADDRESSES",
  ORDERS: "ORDERS",
  VERIFY_PAYMENT_TRANSACTION: "VERIFY_PAYMENT_TRANSACTION",
  CATEGORIES: "CATEGORIES",
  NEWEST_CATEGORY: "NEWEST_CATEGORY",
  BRANDS: "BRANDS",
  ATTRIBUTES: "ATTRIBUTES",
  USERS: "USERS",
};
